import React from "react";

class ImageCard extends React.Component {
	constructor(props) {
		super(props);

        this.state = { spans : 0 };

		// Instead of using i.e. document.querySelector('ref')
        // It's a way to get a handle of an element generated by a tag (in this case: <img>)
		this.imageRef = React.createRef();
	}

    componentDidMount() {
        // 'load' event is standard used when an elements loads, this.setSpans is the callback 
        this.imageRef.current.addEventListener('load', this.setSpans);
    }

    setSpans = () => {
        const height = this.imageRef.current.clientHeight;

        // 10px = grid-auto-rows value assigned in css file
        const spans = Math.ceil(height / 10);

        // same as writing { spans : spans }
        this.setState({ spans });
    }

	render() {
		const { description, urls } = this.props.image;
		return (
			<div style={{ gridRowEnd: `span ${this.state.spans}`}}>
				<img ref={this.imageRef} alt={description} src={urls.regular} />
			</div>
		);
	}
}

export default ImageCard;
